# Generated by Django 5.1.2 on 2024-10-26 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tiendas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreProducto', models.CharField(max_length=100)),
                ('descripcionProducto', models.CharField(max_length=255)),
                ('tipoProducto', models.CharField(max_length=25)),
                ('precioProducto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('imagenUrlProducto', models.CharField(max_length=255)),
                ('estadoProducto', models.BooleanField()),
                ('idTienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='tiendas.tienda')),
            ],
            options={
                'db_table': 'producto',
            },
        ),
    ]
