# Generated by Django 5.1.2 on 2024-10-30 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_alter_producto_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagenUrlProducto',
            field=models.ImageField(upload_to='imagenes/'),
        ),
    ]
