# Generated by Django 5.1.2 on 2024-10-30 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendas', '0003_tienda_urlimgtienda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tienda',
            name='UrlImgTienda',
            field=models.ImageField(upload_to='imagenes/'),
        ),
    ]
